options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/github.com/abdoelboshy/whisper-test:$COMMIT_SHA', '.']
    dir: whisper-container

images:
  - 'gcr.io/$PROJECT_ID/github.com/abdoelboshy/whisper-test:$COMMIT_SHA'
